apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo
  labels:
    app: go-echo
  namespace: devhub-e2e-test-id-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-echo
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
        - name: go-echo
          image: devhube2eycofwdjd.azurecr.io/kubeimage:latest:latest
          ports:
            - containerPort: 1323